### ISSUE TITLE
The editor is giving me an error when I try to execute it right before opening

### ISSUE THREAD

**Issue by LOuroboros** [M3rein/Pokemon-MK#3]
So, the editor is definitely looking fine now. However, when I double click the Editor's .exe file, I'm getting this error:
![pokemonengine_2017-12-06_12-28-51](https://user-images.githubusercontent.com/4485172/33669462-4c46f140-da81-11e7-909e-472e68b53f9e.png)

I know, it's in Spanish. That's why I translated what looked like the most important bit.
https://www.hastebin.com/raw/xagirohibo

For what is worth, if I click the "Continue" button the application certainly starts just fine and seems to be working correctly. I just felt like I had to report it because it is an error nonetheless.

**Comment by M3rein** [comment]
While I don't know for sure, I think this is what's happening:

-> The program loads but it's bigger than your screen
-> It resizes itself *before* it has initialized the map that determines the width/height
-> It throws an error because the resize method references the current map.

Should be a pretty easy fix. Let me know if you still get this after I commit.

**Comment by M3rein** [comment]
Fixed.
